[package]
name = "femtovg-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
femtovg = { version = "0.11.2", features = ["wgpu"] }
spin_on = "0.1.1"
winit = { version = "0.29.1" }
wgpu = { version = "23" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.31.0"
glutin-winit = "0.4.0"
raw-window-handle = "0.5.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { version = "0.3", package = "web-sys", features = [
  "console",
  "WebGlContextAttributes",
] }
console_error_panic_hook = "0.1.5"
instant = { version = "0.1", features = ["wasm-bindgen", "now"] }
resource = { version = "0.5.0", features = ["force-static"] }
getrandom = { version = "0.2.2", features = ["js"] }
wgpu = { version = "23", features = ["webgl"] }
wasm-bindgen-futures = { version = "0.4.45" }
wasm-bindgen = "0.2.99"

[features]
wgpu = []
